// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    var $a, $in, $kp;
    $in = $('#in');
    $a = $('#a');
    $kp = $('#kp');
    $in.change(function() {
      var $toast;
      if (!$in.val().length) {
        $toast = $('<span class="toast-error">Brak danych w polu Imię i nazwisko.</span>');
        return Materialize.toast($toast, 2000, 'rounded');
      }
    });
    $a.change(function() {
      var $toast;
      if (!$a.val().length) {
        $toast = $('<span class="toast-error">Brak danych w polu Adres.</span>');
        return Materialize.toast($toast, 2000, 'rounded');
      }
    });
    $kp.change(function() {
      var $toast;
      if (!$kp.val().length) {
        $toast = $('<span class="toast-error">Brak danych w polu Kod pocztowy.</span>');
        return Materialize.toast($toast, 2000, 'rounded');
      }
    });
    return $kp.keyup(function() {
      $kp.css('background-color', 'none');
      if ($kp.val().length >= 6 && $kp.val()[2] === "-") {
        return $kp.css('background-color', 'green');
      }
    });
  });

}).call(this);
