// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    $('.b').hover(function() {
      return $.ajax({
        type: 'GET',
        url: $(this).attr('id') + '.txt',
        success: function(text) {
          return $('#text').text(text);
        }
      });
    });
    return $('.b2').hover(function() {
      return $.ajax({
        type: 'GET',
        dataType: 'xml',
        url: $(this).attr('id') + '.xml',
        success: function(xml) {
          return $('#xml').text($(xml).find("text").text());
        }
      });
    });
  });

}).call(this);
