// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    return $('.dropitm8').hover((function() {
      return $(this).children('.sub').slideDown(150);
    }), (function() {
      return $(this).children('.sub').slideUp(150);
    }));
  });

}).call(this);
